source_rules:
  - path: /home/ubuntu/openexr-tools
    include: "LICENSE|README\\.md"
    exclude: "/\\.|docker"
  - path: /home/ubuntu/openexr-tools/python/openexr_tools
    include: "\\.py$"
  - path: /home/ubuntu/openexr-tools/docker/config
    include: "flake8|prod.lock"
    exclude: "cache|__pypackages__"
rename_rules:
  - regex: "/home/ubuntu/openexr-tools"
    replace: "/home/ubuntu/build/repo"
  - regex: "/python|/docker|/config"
    replace: ""
  - regex: "prod.lock"
    replace: "pdm.lock"
group_rules:
  - name: test
    regex: "(__init__|_test)\\.py$|flake8\\.ini$|\\.lock$"
  - name: prod
    regex: "__init__\\.py$"
line_rules:
  - group: prod
    exclude: test
